import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { readFileSync, readdirSync } from 'node:fs';
const db=new PGlite();
const ids={u:'10000000-0000-4000-8000-000000000001',v:'10000000-0000-4000-8000-000000000002',admin:'20000000-0000-4000-8000-000000000001',teacher:'20000000-0000-4000-8000-000000000002',guardian:'20000000-0000-4000-8000-000000000003',stranger:'20000000-0000-4000-8000-000000000004',room:'30000000-0000-4000-8000-000000000001',room2:'30000000-0000-4000-8000-000000000002',event:'40000000-0000-4000-8000-000000000001'};
let child:string,attendance:string,person:string,call:string;
async function asUser(id:string){await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);`);}
async function command(type:string,data:unknown,key=crypto.randomUUID()){const res=await db.query<{result:{id:string;error?:string}}>('select public.app_command($1,$2::jsonb,$3) as result',[ids.u,JSON.stringify({type,data}),key]);return res.rows[0].result;}
async function snapshot(){const r=await db.query<{result:Record<string,any>}>('select public.app_snapshot($1) as result',[ids.u]);return r.rows[0].result;}
beforeAll(async()=>{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
 for(const file of readdirSync('supabase/migrations').sort())await db.exec(readFileSync(`supabase/migrations/${file}`,'utf8'));
 await db.exec(`alter table auth.users disable trigger on_auth_user_created;`);
 for(const [key,id] of Object.entries(ids).filter(([key])=>['admin','teacher','guardian','stranger'].includes(key))){await db.query('insert into auth.users(id,email) values($1,$2)',[id,`${key}@example.test`]);await db.query('insert into public.profiles(id,name,email) values($1,$2,$3)',[id,key,`${key}@example.test`]);}
 await db.query('insert into public.units(id,name,slug) values($1,$2,$3),($4,$5,$6)',[ids.u,'Unidade fictícia A','a',ids.v,'Unidade fictícia B','b']);
 for(const [user,role,unit] of [[ids.admin,'administrator',ids.u],[ids.teacher,'teacher',ids.u],[ids.guardian,'guardian',ids.u],[ids.stranger,'guardian',ids.v]])await db.query('insert into public.memberships(unit_id,user_id,roles) values($1,$2,$3)',[unit,user,[role]]);
 await db.query('insert into public.classes(id,unit_id,name,room,min_months,max_months,capacity,teacher_ids,created_by) values($1,$2,$3,$4,0,216,2,$5,$6)',[ids.room,ids.u,'Turma fictícia','Sala 01',[ids.teacher],ids.admin]);
 await db.query('insert into public.classes(id,unit_id,name,room,min_months,max_months,capacity,teacher_ids,created_by) values($1,$2,$3,$4,0,216,2,$5,$6)',[ids.room2,ids.u,'Turma restrita','Sala 02',[],ids.admin]);
 await db.query('insert into public.events(id,unit_id,name,starts_at,status,created_by) values($1,$2,$3,now(),$4,$5)',[ids.event,ids.u,'Evento fictício','open',ids.admin]);
},60000);
afterAll(()=>db.close());
describe('Migrations, RLS e transações PostgreSQL',()=>{
 it('cria criança e cuidados com vínculo gestor atômico',async()=>{await asUser(ids.guardian);child=(await command('save_child',{name:'Criança Fictícia',birth_date:'2022-02-10',allergies:'Alergia fictícia',medication:'',needs:'',notes:''})).id;const s=await snapshot();expect(s.children).toHaveLength(1);expect(s.children[0].allergies).toBe('Alergia fictícia');person=s.people[0].id;});
 it('nega outra unidade e esconde criança por UUID conhecido',async()=>{await asUser(ids.stranger);expect((await db.query('select * from public.children where id=$1',[child])).rows).toHaveLength(0);await expect(snapshot()).rejects.toThrow('não autorizado');await expect(command('save_child',{id:child,name:'Invasão',birth_date:'2022-02-10'})).rejects.toThrow();});
 it('nega escrita direta e autoelevação de papel',async()=>{await asUser(ids.guardian);await expect(db.query('update public.memberships set roles=$1 where user_id=$2',[['administrator'],ids.guardian])).rejects.toThrow();await expect(command('set_member',{id:ids.guardian,roles:['administrator'],active:true})).rejects.toThrow();await expect(db.query('select public.server_operation($1,$2)',['session_get','{}'])).rejects.toThrow();});
 it('admin vê cadastro mas não saúde sem atribuição',async()=>{await asUser(ids.admin);const s=await snapshot();expect(s.children).toHaveLength(1);expect(s.children[0].allergies).toBe('');});
 it('check-in é idempotente e impede duplicação por nova chave',async()=>{await asUser(ids.guardian);const data={child_id:child,event_id:ids.event,class_id:ids.room};const key=crypto.randomUUID();attendance=(await command('check_in',data,key)).id;expect((await command('check_in',data,key)).id).toBe(attendance);await expect(command('check_in',data)).rejects.toThrow('já tem');await expect(command('check_in',{...data,class_id:ids.room2},key)).rejects.toThrow('conteúdo diferente');});
 it('professora atribuída recebe e acessa cuidados',async()=>{await asUser(ids.teacher);await command('receive',{id:attendance});const s=await snapshot();expect(s.attendance[0].status).toBe('present');expect(s.children[0].allergies).toBe('Alergia fictícia');});
 it('registra chamado e fila na mesma transação e rejeita duplicata',async()=>{await asUser(ids.teacher);call=(await command('create_call',{attendance_id:attendance,reason:'Favor comparecer',note:'Observação restrita'})).id;await expect(command('create_call',{attendance_id:attendance,reason:'Outro motivo',note:''})).rejects.toThrow('Já existe');const s=await snapshot();expect(s.calls).toHaveLength(1);expect(s.deliveries).toHaveLength(3);await db.exec('reset role');expect((await db.query('select * from private.outbox_jobs where call_id=$1',[call])).rows).toHaveLength(2);});
 it('resposta a caminho confirma e não regride com evento atrasado',async()=>{await asUser(ids.guardian);await command('respond_call',{id:call,status:'on_the_way'});await command('respond_call',{id:call,status:'viewed'});const s=await snapshot();expect(s.calls[0].status).toBe('on_the_way');expect(s.calls[0].acknowledged_at).toBeTruthy();await db.exec('reset role');expect((await db.query('select * from private.outbox_jobs where call_id=$1 and status=$2',[call,'pending'])).rows).toHaveLength(0);});
 it('ocorrência restrita não é automaticamente compartilhada',async()=>{await asUser(ids.teacher);await command('incident',{attendance_id:attendance,category:'Cuidado',description:'Descrição fictícia restrita',shared:false});await asUser(ids.guardian);expect((await snapshot()).incidents).toHaveLength(0);});
 it('código inválido conta tentativa sem concluir saída',async()=>{await asUser(ids.teacher);expect((await command('checkout',{attendance_id:attendance,credential_digest:'f'.repeat(64),person_id:person})).error).toContain('inválido');expect((await snapshot()).attendance[0].status).toBe('present');await db.exec('reset role');const rate=await db.query<{count:number}>('select count from private.rate_limits where key=$1',[`pickup:${ids.teacher}:${attendance}`]);expect(rate.rows[0].count).toBe(1);});
 it('QR não pode ser emitido pela professora e segredo não pode ser lido',async()=>{await asUser(ids.teacher);await expect(db.query('select public.issue_credential($1,$2,$3,$4)',[ids.u,attendance,'a'.repeat(64),'b'.repeat(64)])).rejects.toThrow();await expect(db.query('select * from private.pickup_credentials')).rejects.toThrow();});
 it('retirada consome credencial e finaliza uma única vez',async()=>{await asUser(ids.guardian);await db.query('select public.issue_credential($1,$2,$3,$4)',[ids.u,attendance,'a'.repeat(64),'b'.repeat(64)]);await asUser(ids.teacher);await command('checkout',{attendance_id:attendance,credential_digest:'a'.repeat(64),person_id:person});const s=await snapshot();expect(s.attendance[0].status).toBe('checked_out');expect(s.calls[0].status).toBe('finalized');await expect(command('checkout',{attendance_id:attendance,credential_digest:'a'.repeat(64),person_id:person})).rejects.toThrow();await db.exec('reset role');expect((await db.query('select * from public.check_outs where check_in_id=$1',[attendance])).rows).toHaveLength(1);});
 it('auditoria e idempotência não copiam informações médicas',async()=>{await db.exec('reset role');const a=await db.query('select * from public.audit_logs');const i=await db.query('select * from private.idempotency');expect(JSON.stringify(a.rows)+JSON.stringify(i.rows)).not.toContain('Alergia fictícia');expect(JSON.stringify(a.rows)+JSON.stringify(i.rows)).not.toContain('Descrição fictícia');});
 it('revogação impede acesso em sessão já existente',async()=>{await db.exec('reset role');await db.query('update public.memberships set active=false where user_id=$1',[ids.teacher]);await asUser(ids.teacher);expect((await db.query('select * from public.children')).rows).toHaveLength(0);await expect(snapshot()).rejects.toThrow();});
});

describe('Fila persistente e recibos',()=>{
 let jobs:Array<{job_id:string;lease_token:string;delivery_id:string;channel:string}>;
 let secondAttendance:string,secondCall:string;
 async function server(action:string,data:unknown){await db.exec('reset role;set role service_role');const r=await db.query<{result:any}>('select public.server_operation($1,$2::jsonb) as result',[action,JSON.stringify(data)]);return r.rows[0].result;}
 it('prepara nova entrada e chamado após saída, sem reutilizar código público',async()=>{await db.exec('reset role');await db.query('update public.memberships set active=true where user_id=$1',[ids.teacher]);await asUser(ids.guardian);secondAttendance=(await command('check_in',{child_id:child,event_id:ids.event,class_id:ids.room})).id;const s=await snapshot();expect(new Set(s.attendance.map((a:any)=>a.public_code)).size).toBe(2);await asUser(ids.teacher);await command('receive',{id:secondAttendance});secondCall=(await command('create_call',{attendance_id:secondAttendance,reason:'Compareça à recepção',note:''})).id;});
 it('job só é reclamado uma vez e e-mail respeita prazo',async()=>{jobs=await server('claim_jobs',{});expect(jobs).toHaveLength(1);expect(jobs[0].channel).toBe('push');expect(await server('claim_jobs',{})).toHaveLength(0);});
 it('worker com lease errado não conclui o job',async()=>{expect(await server('finish_job',{...jobs[0],lease_token:crypto.randomUUID(),status:'accepted',retry:false})).toEqual({stale:true});});
 it('falha temporária agenda retentativa e registra tentativa saneada',async()=>{await server('finish_job',{...jobs[0],status:'unknown',retry:true,code:'PUSH_TIMEOUT'});await db.exec('reset role');const r=await db.query<{status:string;run_after:string}>('select status,run_after from private.outbox_jobs where id=$1',[jobs[0].job_id]);expect(r.rows[0].status).toBe('pending');expect(new Date(r.rows[0].run_after).getTime()).toBeGreaterThan(Date.now());expect((await db.query('select * from private.delivery_attempts where job_id=$1',[jobs[0].job_id])).rows).toHaveLength(1);});
 it('confirmação durante processamento impede payload para próximo envio',async()=>{await db.exec('reset role');await db.query('update private.outbox_jobs set run_after=now() where call_id=$1',[secondCall]);jobs=await server('claim_jobs',{});expect(jobs.length).toBeGreaterThan(0);await asUser(ids.guardian);await command('respond_call',{id:secondCall,status:'acknowledged'});expect(await server('job_payload',jobs[0])).toBeNull();});
 it('recibo antes do ID do provedor é reconciliado e não regride por evento atrasado',async()=>{await db.exec('reset role;set role service_role');await db.query('select public.email_receipt($1,$2,$3,$4)',['receipt-1','provider-fake','email.delivered','2026-09-09T20:00:00Z']);await db.exec('reset role');await db.query("update public.deliveries set provider_id='provider-fake',status='accepted' where call_id=$1 and channel='email'",[secondCall]);await db.exec('set role service_role');await db.query('select public.email_receipt($1,$2,$3,$4)',['receipt-2','provider-fake','email.failed','2026-09-09T19:00:00Z']);await db.exec('reset role');const r=await db.query<{status:string}>('select status from public.deliveries where provider_id=$1',['provider-fake']);expect(r.rows[0].status).toBe('delivered');});
 it('revogar autorizado entre leitura e conclusão impede retirada',async()=>{await asUser(ids.guardian);await db.query('select public.issue_credential($1,$2,$3,$4)',[ids.u,secondAttendance,'c'.repeat(64),'d'.repeat(64)]);await command('revoke_person',{id:person});await asUser(ids.teacher);await expect(command('checkout',{attendance_id:secondAttendance,credential_digest:'c'.repeat(64),person_id:person})).rejects.toThrow('Pessoa não autorizada');expect((await snapshot()).attendance.find((a:any)=>a.id===secondAttendance).status).toBe('present');});
 it('capacidade e encerramento de evento respeitam presenças',async()=>{await asUser(ids.guardian);const b=(await command('save_child',{name:'Segunda Fictícia',birth_date:'2022-02-10'})).id;const c=(await command('save_child',{name:'Terceira Fictícia',birth_date:'2022-02-10'})).id;await command('check_in',{child_id:b,event_id:ids.event,class_id:ids.room});await expect(command('check_in',{child_id:c,event_id:ids.event,class_id:ids.room})).rejects.toThrow('lotada');await asUser(ids.admin);await expect(command('save_event',{id:ids.event,name:'Evento fictício',starts_at:new Date().toISOString(),status:'closed'})).rejects.toThrow('Há crianças');});
});
