import { beforeEach, describe, expect, it, vi } from 'vitest';
import { encrypt, decrypt, issuePickup, pickupDigest, validPushEndpoint, hash } from '../server/security';
import { ResendProvider } from '../server/integrations/email';
import { HolyricsAdapter } from '../server/integrations/holyrics';
import { publicAlertSchema } from '../shared/integrations';
import { childSchema, ageMonths } from '../shared/domain';
import { DemoRepository } from '../src/lib/demo';
beforeEach(()=>{process.env.SESSION_ENCRYPTION_KEY=Buffer.alloc(32,7).toString('base64');process.env.PICKUP_SIGNING_SECRET='test-only-secret-never-use-in-production-123456789';});
describe('Credenciais e sessão',()=>{
 it('cifra autenticada não contém token e rejeita adulteração',()=>{const encrypted=encrypt({refresh_token:'sensitive-fake-token'});expect(encrypted).not.toContain('sensitive');expect(decrypt(encrypted)).toEqual({refresh_token:'sensitive-fake-token'});const changed=Buffer.from(encrypted,'base64url');changed[changed.length-1]^=1;expect(()=>decrypt(changed.toString('base64url'))).toThrow();});
 it('QR assinado é vinculado à presença e diferente a cada emissão',async()=>{const a=await issuePickup('attendance-a');const b=await issuePickup('attendance-a');expect(a.token).not.toBe(b.token);expect(await pickupDigest(a.token,'attendance-a')).toBe(a.digest);expect(await pickupDigest(a.numeric,'attendance-a')).toBe(a.numeric_digest);await expect(pickupDigest(a.token,'attendance-b')).rejects.toThrow();await expect(pickupDigest(a.token+'x','attendance-a')).rejects.toThrow();});
 it('endpoints push não permitem SSRF ou redirecionamento a host arbitrário',()=>{for(const endpoint of ['http://localhost','https://127.0.0.1/x','https://169.254.169.254/latest','https://fcm.googleapis.com.evil.test/x','https://user:pass@fcm.googleapis.com/x','https://fcm.googleapis.com:8443/x'])expect(validPushEndpoint(endpoint)).toBe(false);expect(validPushEndpoint('https://fcm.googleapis.com/fcm/send/fake')).toBe(true);});
});
describe('Adaptadores externos sem rede real',()=>{
 it('e-mail discreto usa idempotência e não recebe informação médica',async()=>{const transport=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:'fake-provider-id'}),{status:200}));const result=await new ResendProvider('fake','demo@example.test','https://example.test',transport).send('guardian@example.test','delivery-key');expect(result.status).toBe('accepted');const options=transport.mock.calls[0][1];expect(options.headers['Idempotency-Key']).toBe('delivery-key');expect(JSON.parse(options.body).text).not.toContain('alergia');});
 it('limitação permite retry, erro permanente não',async()=>{for(const [status,retry] of [[429,true],[500,true],[422,false]] as const){const transport=vi.fn().mockResolvedValue(new Response('{}',{status}));expect((await new ResendProvider('fake','a@example.test','https://example.test',transport).send('b@example.test','key')).retry).toBe(retry);}});
 it('timeout de envio é desconhecido, não entregue',async()=>{const transport=vi.fn().mockRejectedValue(new Error('network'));expect(await new ResendProvider('fake','a@example.test','https://example.test',transport).send('b@example.test','key')).toMatchObject({status:'unknown',retry:true});});
 it('Holyrics desativado nunca chama transporte',async()=>{const transport=vi.fn();const adapter=new HolyricsAdapter({enabled:false},transport);expect((await adapter.publish({publicCode:'E-127',expiresAt:new Date(Date.now()+60000).toISOString(),durationSeconds:10,mode:'automatic'})).status).toBe('disabled');await adapter.hide();expect(transport).not.toHaveBeenCalled();});
 it('contrato não aceita nome, sala ou informação médica',()=>{expect(()=>publicAlertSchema.parse({publicCode:'E-127',expiresAt:new Date().toISOString(),durationSeconds:10,mode:'automatic',name:'Nome pessoal'})).toThrow();});
 it('aprovação da mídia não é declarada exibição concluída',async()=>{const transport=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'ok',response_status:'ok',response:{status:'ok'}})));const adapter=new HolyricsAdapter({enabled:true,apiKey:'fake',token:'fake'},transport);expect((await adapter.publish({publicCode:'E-127',expiresAt:new Date(Date.now()+60000).toISOString(),durationSeconds:10,mode:'media_approval'})).status).toBe('awaiting_approval');expect(transport.mock.calls[0][0]).toContain('ShowCustomMessageStandalone');const payload=JSON.parse(transport.mock.calls[0][1].body);expect(payload.message).toContain('E-127');expect(payload.params).toEqual([]);});
 it('computador desconectado e timeout são diferenciados',async()=>{const transport=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'error',error:{key:'device_disconnected'}})));const adapter=new HolyricsAdapter({enabled:true,apiKey:'fake',token:'fake'},transport);expect((await adapter.hide()).connectionStatus).toBe('disconnected');});
 it('código público expirado não é enviado',async()=>{const transport=vi.fn();const adapter=new HolyricsAdapter({enabled:true,apiKey:'fake',token:'fake'},transport);expect((await adapter.publish({publicCode:'E-127',expiresAt:new Date(Date.now()-1000).toISOString(),durationSeconds:10,mode:'automatic'})).status).toBe('expired');expect(transport).not.toHaveBeenCalled();});
});
describe('Domínio e demonstração',()=>{
 it('valida datas impossíveis, nascimento futuro e campos grandes',()=>{expect(childSchema.safeParse({name:'Teste',birth_date:'2024-02-31'}).success).toBe(false);expect(childSchema.safeParse({name:'Teste',birth_date:'2099-01-01'}).success).toBe(false);expect(childSchema.safeParse({name:'Teste',birth_date:'2022-01-01',allergies:'a'.repeat(1001)}).success).toBe(false);expect(ageMonths('2022-06-15',new Date(2026,5,14))).toBe(47);});
 it('demonstração filtra famílias e turmas por perfil',()=>{const repo=new DemoRepository();repo.switchRole('guardian');expect(repo.snapshot().children).toHaveLength(2);repo.switchRole('teacher');expect(repo.snapshot().classes.every(c=>c.teacher_ids.includes('teacher'))).toBe(true);});
 it('código público não autoriza retirada',()=>{const repo=new DemoRepository();repo.switchRole('teacher');expect(()=>repo.command({type:'checkout',data:{attendance_id:'attendance-0',credential:'E-127000',person_id:'person-0'}},crypto.randomUUID())).toThrow('Código inválido');});
});

describe('Webhook de e-mail',()=>{
 it('valida assinatura, corpo intacto e janela temporal',async()=>{const {Webhook}=await import('svix');const {verifyEmailWebhook}=await import('../server/webhooks');const secret='whsec_'+Buffer.alloc(32,9).toString('base64');process.env.RESEND_WEBHOOK_SECRET=secret;const payload=JSON.stringify({type:'email.delivered',created_at:new Date().toISOString(),data:{email_id:'fake-message'}});const date=new Date();const signature=new Webhook(secret).sign('msg_fake',date,payload);const headers=new Headers({'svix-id':'msg_fake','svix-timestamp':String(Math.floor(date.getTime()/1000)),'svix-signature':signature});expect(verifyEmailWebhook(payload,headers).type).toBe('email.delivered');expect(()=>verifyEmailWebhook(payload+' ',headers)).toThrow();headers.set('svix-timestamp','1');expect(()=>verifyEmailWebhook(payload,headers)).toThrow();});
});
