import { createHash, createHmac, randomBytes, randomInt, createCipheriv, createDecipheriv } from 'node:crypto';
import { SignJWT, jwtVerify } from 'jose';
export const hash=(input:string)=>createHash('sha256').update(input).digest('hex');
export function secret(name:string){const value=process.env[name];if(!value)throw new Error(`Configuração de servidor ausente: ${name}`);return value;}
export function encrypt(value:unknown){const key=Buffer.from(secret('SESSION_ENCRYPTION_KEY'),'base64');if(key.length!==32)throw new Error('Chave de sessão inválida.');const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key,iv);const body=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64url');}
export function decrypt<T>(encrypted:string):T{const all=Buffer.from(encrypted,'base64url');const decipher=createDecipheriv('aes-256-gcm',Buffer.from(secret('SESSION_ENCRYPTION_KEY'),'base64'),all.subarray(0,12));decipher.setAuthTag(all.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(all.subarray(28)),decipher.final()]).toString('utf8')) as T;}
export function numericDigest(code:string,attendanceId:string){return createHmac('sha256',secret('PICKUP_SIGNING_SECRET')).update(`${attendanceId}:${code}`).digest('hex');}
export async function issuePickup(attendanceId:string){const token=await new SignJWT({attendance:attendanceId}).setProtectedHeader({alg:'HS256',typ:'JWT'}).setIssuer('escolinha').setAudience('pickup').setJti(randomBytes(24).toString('base64url')).setIssuedAt().setExpirationTime('10m').sign(new TextEncoder().encode(secret('PICKUP_SIGNING_SECRET')));const numeric=String(randomInt(10000000,100000000));return {token,numeric,digest:hash(token),numeric_digest:numericDigest(numeric,attendanceId)};}
export async function pickupDigest(token:string,attendanceId:string){if(/^\d{8}$/.test(token))return numericDigest(token,attendanceId);try{const verified=await jwtVerify(token,new TextEncoder().encode(secret('PICKUP_SIGNING_SECRET')),{algorithms:['HS256'],issuer:'escolinha',audience:'pickup'});if(verified.payload.attendance!==attendanceId)throw new Error();return hash(token);}catch{throw new Error('Código inválido ou expirado.');}}
export function allowedOrigin(origin:string|null){return origin===secret('APP_ORIGIN');}
export function validPushEndpoint(endpoint:string){try{const u=new URL(endpoint);return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&(u.hostname==='fcm.googleapis.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname.endsWith('.push.apple.com')||u.hostname==='web.push.apple.com'||u.hostname==='wns.windows.com'||u.hostname.endsWith('.notify.windows.com'));}catch{return false;}}
