import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Users, LogIn, LogOut, Bell, Plus, Check, ShieldCheck, Heart, Sprout, Sun, Star, Clock, QrCode } from 'lucide-react';
import { useApp } from '../lib/app';
import { activeAttendance, activeCall } from '../../shared/domain';
import { Avatar, ChildAvatar, Badge, PageTitle, Panel, Empty, time } from '../components/ui';
export function Dashboard(){const {data:s,role,selectedEvent}=useApp();if(!s)return null;
 const attendance=s.attendance.filter(a=>a.event_id===selectedEvent);const present=attendance.filter(a=>['present','pickup_requested'].includes(a.status));const calls=s.calls.filter(c=>activeCall(c)&&attendance.some(a=>a.id===c.attendance_id));const event=s.events.find(e=>e.id===selectedEvent);
 if(role==='guardian')return <><PageTitle eyebrow="QUE BOM TER VOCÊ AQUI" title={`Olá, ${s.current_user.name.split(' ')[0]} ☀`} description="Um lugar de cuidado, descobertas e muito amor."/><section className="welcome-banner family-banner"><div><span className="banner-tag"><Heart size={14}/> SUA FAMÍLIA É BEM-VINDA</span><h2>Pequenos passos.<br/>Grandes descobertas.</h2><p>Acompanhe seus filhos e fique pertinho,<br/>mesmo durante o culto.</p><Link to="/check-in" className="button">Fazer check-in <ArrowRight size={17}/></Link></div><Garden/></section>{calls.length>0&&<Link to="/chamados" className="call-alert"><Bell size={22}/><span><strong>A equipe solicita sua presença</strong><small>Abra o chamado para ver os detalhes e responder.</small></span><ArrowRight size={20}/></Link>}<Panel title="Meus filhos" subtitle="Tudo bem por aqui. Acompanhe cada momento." action={<Link to="/criancas" className="text-link">Gerenciar <ArrowRight size={15}/></Link>}><div className="family-grid">{s.children.filter(c=>c.active).map(c=>{const a=attendance.find(a=>a.child_id===c.id&&activeAttendance(a));return <div className="family-card" key={c.id}><ChildAvatar child={c}/><h3>{c.name}</h3><p>{a?s.classes.find(r=>r.id===a.class_id)?.name:'Pronto para uma nova descoberta'}</p>{a?<><Badge status={a.status}/><Link className="button secondary" to={`/retirada/${a.id}`}><QrCode size={17}/>Comprovante e retirada</Link></>:<Link to={`/check-in?child=${c.id}`} className="button secondary"><LogIn size={17}/> Fazer check-in</Link>}</div>;})}</div></Panel></>;
 return <><PageTitle title={`Olá, ${s.current_user.name.split(' ')[0]}!`} description="Vamos cuidar de mais um dia especial?" action={<Link to="/check-in" className="button"><Plus size={18}/> Novo check-in</Link>}/><section className="welcome-banner"><div><span className="banner-tag"><Sun size={15}/> CADA CRIANÇA, UM NOVO COMEÇO</span><h2>Um pequeno lugar.<br/>Um amor que transforma.</h2><p>Hoje é dia de acolher, ensinar e crescer juntos.<br/>Tudo o que você precisa para cuidar está aqui.</p><div className="banner-meta"><span><span className="live-dot"/>{event?.name??'Escolinha'}</span><span><Clock size={14}/>{event?time(event.starts_at):'—'}</span></div></div><Garden/></section>
 <div className="stats-grid">{[{label:'Crianças presentes',value:present.length,icon:Users,color:'green',foot:'Sorrisos que alegram nossa casa',sub:'Agora'},{label:'Check-ins realizados',value:attendance.filter(a=>a.status!=='cancelled').length,icon:LogIn,color:'blue',foot:`${attendance.filter(a=>a.status==='pending_reception').length} aguardando recebimento`,sub:'Hoje'},{label:'Chamados ativos',value:calls.length,icon:Bell,color:'orange',foot:calls.length?'Precisam da nossa atenção':'Tudo tranquilo por aqui',sub:'Acompanhar'},{label:'Retiradas concluídas',value:attendance.filter(a=>a.status==='checked_out').length,icon:LogOut,color:'purple',foot:'Entregues com cuidado e segurança',sub:'Hoje'}].map(stat=><Link to={stat.label==='Chamados ativos'?'/chamados':'/presencas'} className="stat-card" key={stat.label}><div className="stat-top"><span>{stat.label}</span><span className={`stat-icon ${stat.color}`}><stat.icon size={19}/></span></div><div className="stat-value">{String(stat.value).padStart(2,'0')}<span>{stat.sub}</span></div><p>{stat.foot}</p></Link>)}</div>
 <div className="dashboard-columns"><Panel title="Nossas turmas" subtitle="Cada fase tem seu espaço para florescer." action={<Link className="text-link" to="/turmas">Ver todas <ArrowRight size={15}/></Link>}><div className="class-list">{s.classes.filter(c=>c.active).map((c,index)=>{const count=present.filter(a=>a.class_id===c.id).length;const Icon=[Sprout,Sun,Star][index%3];return <Link key={c.id} to={`/presencas?class=${c.id}`} className="class-row"><span className={`class-icon ${c.color}`}><Icon size={23}/></span><div className="class-info"><h3>{c.name}</h3><p>{c.room} <span>·</span> {Math.floor(c.min_months/12)} a {Math.ceil(c.max_months/12)-1} anos</p></div><div className="class-occupancy"><strong>{count}<span> / {c.capacity}</span></strong><div className="progress-track"><i className={c.color} style={{width:`${count/c.capacity*100}%`}}/></div></div><ArrowUpRight size={17}/></Link>;})}</div><div className="panel-foot"><ShieldCheck size={16}/> Cuidado especial em cada faixa etária.</div></Panel>
 <Panel title="Chamados em andamento" subtitle="Conexão com quem cuida." action={<span className="count-pill">{calls.length}</span>}>{calls.length?calls.slice(0,3).map(c=>{const child=s.children.find(ch=>ch.id===c.child_id);return <Link to={`/chamados?call=${c.id}`} className="call-preview" key={c.id}>{child?<ChildAvatar child={child} color={c.status==='on_the_way'?'purple':'orange'} small/>:<Avatar name="Criança" color={c.status==='on_the_way'?'purple':'orange'} small/>}<div><h3>{child?.name}</h3><p>{s.classes.find(r=>r.id===attendance.find(a=>a.id===c.attendance_id)?.class_id)?.name}</p><Badge status={c.status}/></div><time>{time(c.created_at)}</time></Link>;}):<Empty title="Tudo tranquilo" description="Nenhum chamado aguardando resposta."/>}<Link to="/chamados" className="panel-link">Acompanhar chamados <ArrowRight size={16}/></Link></Panel></div>
 <Panel title="Últimas chegadas" subtitle="Cada chegada é motivo de alegria." action={<Link to="/presencas" className="text-link">Ver todas as crianças <ArrowRight size={15}/></Link>}><div className="table-scroll"><table><thead><tr><th>Criança</th><th>Turma</th><th>Responsável</th><th>Entrada</th><th>Status</th><th><span className="sr-only">Ação</span></th></tr></thead><tbody>{[...attendance].sort((a,b)=>b.requested_at.localeCompare(a.requested_at)).slice(0,4).map(a=>{const c=s.children.find(c=>c.id===a.child_id);return <tr key={a.id}><td><div className="person-cell">{c?<ChildAvatar child={c} small/>:<Avatar name="Criança" small/>}<strong>{c?.name}</strong></div></td><td>{s.classes.find(c=>c.id===a.class_id)?.name}</td><td>{c?.guardian_name}</td><td>{time(a.requested_at)}</td><td><Badge status={a.status}/></td><td><Link className="icon-button" aria-label={`Ver ${c?.name}`} to={`/presencas?child=${a.child_id}`}><ArrowUpRight size={17}/></Link></td></tr>;})}</tbody></table></div></Panel>
 <div className="verse"><Heart size={16}/><p>“Deixai vir a mim os pequeninos.” <span>Marcos 10:14</span></p></div></>;
}
function Garden(){return <div className="garden" aria-hidden="true"><div className="garden-orbit"/><div className="garden-sun"><Sun size={49} strokeWidth={1.2}/></div><div className="garden-spark one">✧</div><div className="garden-spark two">✧</div><svg viewBox="0 0 340 225"><path d="M25 202 Q165 164 312 205" stroke="#cfddd0" fill="none" strokeWidth="2"/><path d="M170 195 Q160 141 174 62" fill="none" stroke="#477760" strokeWidth="5" strokeLinecap="round"/><path d="M174 114C113 119 103 75 108 60c44-2 72 13 66 54" fill="#7eaa8a"/><path d="M171 143c4-60 50-65 77-53-3 37-27 59-77 53" fill="#4d8368"/><path d="M174 77c-5-49 23-66 48-62 9 36-9 62-48 62" fill="#b2c89c"/><path d="M105 199q5-30-3-60" stroke="#977955" fill="none" strokeWidth="4"/><path d="M104 170c-36 0-50-19-45-38 28-3 48 13 45 38" fill="#e3b778"/><path d="M104 154c2-28 25-40 44-29-5 24-20 30-44 29" fill="#f0ce94"/><path d="M235 202q-1-19 8-46" stroke="#8a8c6e" fill="none" strokeWidth="3"/><path d="M241 173c-23 1-36-12-31-26 22-2 31 8 31 26" fill="#a9bba0"/><path d="M241 166c2-22 20-28 34-20-3 16-16 23-34 20" fill="#c6d6b7"/><ellipse cx="171" cy="207" rx="92" ry="5" fill="#d5dfd0" opacity=".5"/></svg><span className="garden-note"><Heart size={13}/> Cultivando amor e fé</span></div>;}
