import { useEffect, useRef, useState, type FormEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Heart, ImagePlus, MessageCircle, MoreHorizontal, Plus, Send, ShieldCheck, Trash2, Upload, X } from 'lucide-react';
import { api, useApp } from '../lib/app';
import { Badge, Empty, Loading, Modal, PageTitle, Panel } from '../components/ui';

type Photo={id:string;album_id:string;url:string|null;thumbnail_url:string|null;caption:string;like_count:number;liked_by_me:boolean;storage_path:string};
type Comment={id:string;photo_id:string;user_id:string;parent_comment_id:string|null;content:string;status:string;edited_at?:string;created_at:string};
type Album={id:string;unit_id:string;title:string;description:string;service_date:string;status:string;created_by:string;photos:Photo[];comments:Comment[]};
const dateLabel=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'});
const callApi=async(action:string,data:Record<string,unknown>)=>api<{id?:string;ok?:boolean}>('worship',{action,data,idempotency_key:crypto.randomUUID()});

async function compress(file:File){return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Não foi possível ler a imagem.'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('Formato de imagem inválido.'));image.onload=()=>{const scale=Math.min(1,1800/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/webp',.82));};image.src=String(reader.result);};reader.readAsDataURL(file);});}

function AlbumCard({album,onOpen}:{album:Album;onOpen:()=>void}){const cover=album.photos[0]?.thumbnail_url??album.photos[0]?.url;return <button className="worship-card" onClick={onOpen}><div className="worship-cover">{cover?<img src={cover} alt="" loading="lazy"/>:<ImagePlus size={28}/>}<span>{album.photos.length} {album.photos.length===1?'foto':'fotos'}</span></div><div className="worship-card-body"><Badge status={album.status}>{album.status==='published'?'Publicado':album.status}</Badge><h2>{album.title}</h2><p>{dateLabel(album.service_date)}</p>{album.description&&<small>{album.description}</small>}</div></button>}

function CreateAlbum({onDone,onClose}:{onDone:()=>void;onClose:()=>void}){const {toast}=useApp();const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [serviceDate,setServiceDate]=useState(new Date().toISOString().slice(0,10));const [files,setFiles]=useState<File[]>([]);const [uploaded,setUploaded]=useState<{id:string;name:string;status:string}[]>([]);const [albumId,setAlbumId]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [consent,setConsent]=useState(false);const input=useRef<HTMLInputElement>(null);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!files.length&&!albumId){toast('Adicione pelo menos uma foto.',true);return;}setBusy(true);try{if(albumId){await callApi('publish_album',{id:albumId,consent_confirmed:consent});toast('Álbum publicado para os responsáveis.');onDone();return;}const created=await callApi('create_album',{title,description,service_date:serviceDate});const createdAlbumId=created.id!;for(const [index,file] of files.entries()){setUploaded(v=>[...v,{id:`upload-${index}`,name:file.name,status:'Enviando…'}]);const data=await compress(file);const photo=await api<{id:string}>('worship-photo',{album_id:createdAlbumId,photo_id:crypto.randomUUID(),sort_order:index,data,caption:''});setUploaded(v=>v.map(item=>item.name===file.name?{...item,id:photo.id,status:'Enviado'}:item));}setAlbumId(createdAlbumId);setFiles([]);toast('Fotos enviadas. Revise e confirme a publicação.');}catch(error){toast(error instanceof Error?error.message:'Não foi possível enviar as fotos.',true);}finally{setBusy(false);}};
 const removeUploaded=async(item:{id:string;name:string;status:string})=>{if(!albumId||item.id.startsWith('upload-'))return;setBusy(true);try{await callApi('delete_photo',{id:item.id});setUploaded(v=>v.filter(photo=>photo.id!==item.id));}catch(error){toast(error instanceof Error?error.message:'Não foi possível remover a foto.',true);}finally{setBusy(false);}};
 return <Modal title="Novo momento do culto" description="Publique fotos acolhedoras para toda a comunidade da unidade." onClose={onClose}><form className="padded" onSubmit={submit}><label>Título<input value={title} onChange={e=>setTitle(e.target.value)} minLength={2} maxLength={120} required placeholder="Ex.: Culto da família"/></label><label>Data do culto<input type="date" value={serviceDate} onChange={e=>setServiceDate(e.target.value)} required/></label><label>Descrição opcional<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={1000} rows={3}/></label><div className="worship-upload"><input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles(Array.from(e.target.files??[]).filter(file=>file.size<=8*1024*1024))}/><button type="button" className="button secondary" onClick={()=>input.current?.click()} disabled={busy}><Upload size={17}/>Selecionar fotos</button>{files.length>0&&<p>{files.length} foto(s) aguardando envio</p>}{files.map(file=><div className="upload-row" key={file.name}><span>{file.name}</span><button type="button" className="icon-button" aria-label={`Remover ${file.name}`} onClick={()=>setFiles(v=>v.filter(item=>item!==file))}><X size={15}/></button></div>)}{uploaded.map(file=><div className="upload-row" key={file.id}><span>{file.name} · {file.status}</span><button type="button" className="icon-button" aria-label={`Remover ${file.name}`} onClick={()=>void removeUploaded(file)} disabled={busy}><Trash2 size={15}/></button></div>)}</div><label className="checkbox-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><ShieldCheck size={16}/> Confirmei que as imagens podem ser compartilhadas com os responsáveis ativos desta unidade e não contêm informações pessoais indevidas.</label><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button" disabled={busy}>{busy?(albumId?'Publicando…':'Enviando…'):(albumId?'Publicar álbum':'Enviar fotos')}</button></div></form></Modal>}

function PhotoInteractions({album,photo,onRefresh}:{album:Album;photo:Photo;onRefresh:()=>void}){const {data:s,toast}=useApp();const [content,setContent]=useState('');const [replyTo,setReplyTo]=useState<string|null>(null);const comments=album.comments.filter(c=>c.photo_id===photo.id);const act=async(action:string,data:Record<string,unknown>)=>{try{await callApi(action,data);onRefresh();}catch(error){toast(error instanceof Error?error.message:'Não foi possível concluir.',true);}};return <div className="worship-interactions"><div className="worship-actions"><button className={`icon-button ${photo.liked_by_me?'liked':''}`} aria-label={photo.liked_by_me?'Retirar curtida':'Curtir foto'} onClick={()=>void act(photo.liked_by_me?'unlike':'like',{photo_id:photo.id})}><Heart size={19} fill={photo.liked_by_me?'currentColor':'none'}/><span>{photo.like_count}</span></button><span><MessageCircle size={18}/>{comments.length}</span></div><div className="worship-comments">{comments.map(comment=>comment.status==='published'?<div className="worship-comment" key={comment.id}><div><strong>{comment.user_id===s?.current_user.id?'Você':'Responsável'}</strong>{comment.edited_at&&<small> · editado</small>}<p>{comment.content}</p>{!comment.parent_comment_id&&<button type="button" className="text-link" onClick={()=>setReplyTo(comment.id)}>Responder</button>}</div><div className="row-actions">{comment.user_id===s?.current_user.id&&<button className="icon-button" aria-label="Excluir comentário" onClick={()=>void act('delete_comment',{id:comment.id})}><Trash2 size={15}/></button>}<button className="icon-button" aria-label="Denunciar comentário" onClick={()=>void act('report_comment',{comment_id:comment.id,reason:'other',details:'Denúncia enviada pelo mural.'})}><MoreHorizontal size={15}/></button></div></div>:<div className="worship-comment muted" key={comment.id}><p>{comment.status==='removed_by_author'?'Comentário removido pelo autor.':'Comentário removido pela moderação.'}</p></div>)}<form className="comment-form" onSubmit={e=>{e.preventDefault();if(content.trim())void act('comment',{photo_id:photo.id,parent_comment_id:replyTo,content:content.trim()}).then(()=>{setContent('');setReplyTo(null);});}}><input aria-label="Escreva um comentário" maxLength={500} value={content} onChange={e=>setContent(e.target.value)} placeholder={replyTo?'Escreva uma resposta…':'Escreva um comentário…'}/><button className="icon-button" aria-label="Enviar comentário" disabled={!content.trim()}><Send size={17}/></button></form></div></div>}

export function WorshipPage(){const {role,toast}=useApp();const navigate=useNavigate();const [albums,setAlbums]=useState<Album[]|null>(null);const [notifications,setNotifications]=useState<Array<{id:string;album_id:string;created_at:string}>>([]);const [create,setCreate]=useState(false);const [loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{const result=await api<{albums:Album[]}>('worship');setAlbums(result.albums);if(role==='guardian'){const notices=await api<{notifications:Array<{id:string;album_id:string;created_at:string}>}>('worship-notifications');setNotifications(notices.notifications);}}catch(error){toast(error instanceof Error?error.message:'Não foi possível carregar o mural.',true);}finally{setLoading(false);}};useEffect(()=>{void load();},[role]);if(loading)return <Loading/>;const visible=(albums??[]).filter(a=>role==='guardian'?a.status==='published':true);return <><PageTitle eyebrow="MEMÓRIAS QUE ACOLHEM" title="Momentos do Culto" description="Fotos especiais da Escolinha para guardar e compartilhar em família." action={(role==='teacher'||role==='administrator')&&<button className="button" onClick={()=>setCreate(true)}><Plus size={17}/>Novo álbum</button>}/>{notifications.length>0&&role==='guardian'&&<div className="form-notice"><ShieldCheck size={18}/> Há {notifications.length} publicação(ões) nova(s) no mural.</div>}{visible.length?<><div className="worship-grid">{visible.map(album=><AlbumCard key={album.id} album={album} onOpen={()=>navigate(`/momentos/${album.id}`)}/>)}</div></>:<Panel><Empty title="Ainda não há momentos publicados" description="Quando a equipe publicar fotos de um culto, elas aparecerão aqui."/></Panel>}{create&&<CreateAlbum onClose={()=>setCreate(false)} onDone={()=>{setCreate(false);void load();}}/>}</>}

export function WorshipAlbumPage(){const {id}=useParams();const navigate=useNavigate();const {toast}=useApp();const [album,setAlbum]=useState<Album|null>(null);const [loading,setLoading]=useState(true);const load=async()=>{try{const result=await api<{albums:Album[]}>(`worship?album_id=${encodeURIComponent(id??'')}`);setAlbum(result.albums[0]??null);}catch(error){toast(error instanceof Error?error.message:'Não foi possível carregar o álbum.',true);}finally{setLoading(false);}};useEffect(()=>{void load();},[id]);if(loading)return <Loading/>;if(!album)return <Empty title="Álbum não encontrado" action={<button className="button" onClick={()=>navigate('/momentos')}>Voltar</button>}/>;return <><button className="text-link worship-back" onClick={()=>navigate('/momentos')}><ArrowLeft size={16}/>Momentos do Culto</button><PageTitle title={album.title} description={`${dateLabel(album.service_date)}${album.description?` · ${album.description}`:''}`}/><div className="worship-photo-grid">{album.photos.map(photo=><article className="worship-photo-card" key={photo.id}><button className="worship-photo-open" onClick={()=>photo.url&&window.open(photo.url,'_blank','noopener,noreferrer')}><img src={photo.thumbnail_url??photo.url??''} alt={photo.caption||`Foto do álbum ${album.title}`} loading="lazy"/></button>{photo.caption&&<p>{photo.caption}</p>}<PhotoInteractions album={album} photo={photo} onRefresh={()=>void load()}/></article>)}</div></>}

export function WorshipModerationPage(){const {toast}=useApp();const [reports,setReports]=useState<Array<{id:string;comment_id:string;reason:string;details:string;reported_by:string;created_at:string}>>([]);const load=async()=>{try{const result=await api<{reports:typeof reports}>('worship-moderation');setReports(result.reports);}catch(error){toast(error instanceof Error?error.message:'Não foi possível carregar as denúncias.',true);}};useEffect(()=>{void load();},[]);return <><PageTitle title="Moderação dos Momentos" description="Analise denúncias e mantenha o mural acolhedor."/><Panel>{reports.length?reports.map(report=><div className="moderation-row" key={report.id}><div><strong>Comentário denunciado</strong><p>{report.reason} · {report.details||'Sem detalhes adicionais.'}</p><small>{new Date(report.created_at).toLocaleString('pt-BR')}</small></div><div className="row-actions"><button className="button secondary small-button" onClick={async()=>{await callApi('review_report',{report_id:report.id,status:'ignored',resolution:'Denúncia analisada e ignorada.'});await load();}}>Ignorar</button><button className="button small-button" onClick={async()=>{await callApi('moderate_comment',{comment_id:report.comment_id,reason:'Removido após denúncia.'});await load();}}>Remover comentário</button><button className="icon-button" title="Bloquear autor" onClick={async()=>{await callApi('block_user',{user_id:report.reported_by,reason:'Bloqueio temporário por moderação.',blocked_until:new Date(Date.now()+7*86400000).toISOString()});await load();}}>Bloquear</button></div></div>):<Empty title="Nenhuma denúncia pendente" description="As denúncias novas aparecerão aqui para análise."/>}</Panel></>}
