import { NavLink, Outlet, Link, useLocation } from 'react-router-dom';
import { LayoutDashboard, Users, CalendarDays, DoorOpen, Bell, ClipboardList, Settings, LogOut, Heart, ChevronDown, Menu, X, ArrowUpRight, WifiOff, ShieldCheck, Sprout, Download, QrCode, UserRound, History } from 'lucide-react';
import { useState } from 'react';
import { useApp, isDemo } from '../lib/app';
import { Avatar, Logo, Loading } from './ui';
import { PushPrompt } from './PushPrompt';
import { activeCall } from '../../shared/domain';
export function Layout(){const {data,loading,error,role,setRole,selectedEvent,setSelectedEvent,online,logout}=useApp();const [open,setOpen]=useState(false);const location=useLocation();
 if(loading)return <Loading/>;if(!data)return <div className="auth-page"><Logo/><h1>Vamos entrar?</h1><p>{error?.message??'Entre para acessar a Escolinha.'}</p><Link className="button" to="/login">Acessar minha conta</Link></div>;
 const links=role==='guardian'?[['/','Início',LayoutDashboard],['/criancas','Meus filhos',Heart],['/chamados','Chamados',Bell],['/historico','Histórico',History],['/configuracoes','Meu perfil',UserRound]] as const:[['/','Visão geral',LayoutDashboard],['/presencas','Crianças presentes',Users],['/turmas','Salas e turmas',DoorOpen],['/chamados','Chamados',Bell],['/ocorrencias','Ocorrências',ClipboardList],['/historico','Histórico',History]] as const;
 const calls=data.calls.filter(activeCall).length;
 return <div className={`app-shell role-${role}`}><a className="skip-link" href="#main">Pular para o conteúdo</a>{open&&<button className="sidebar-scrim" aria-label="Fechar menu" onClick={()=>setOpen(false)}/>}
 <aside className={`sidebar ${open?'is-open':''}`}><Link to="/" className="brand-link" aria-label="Escolinha, início"><Logo/></Link><button className="mobile-close icon-button" onClick={()=>setOpen(false)} aria-label="Fechar menu"><X/></button><div className="unit-label"><span className="unit-symbol"><Heart size={16}/></span><span>Ministério infantil<small>Unidade principal</small></span><ChevronDown size={15}/></div><div className="nav-section">{role==='guardian'?'MINHA FAMÍLIA':'ACOMPANHAMENTO'}</div><nav aria-label="Navegação principal">{links.map(([path,label,Icon])=><NavLink key={path} to={path} end={path==='/'} onClick={()=>setOpen(false)}><Icon size={19}/><span>{label}</span>{path==='/chamados'&&calls>0&&<span className="nav-count">{calls}</span>}</NavLink>)}</nav>
 {role==='administrator'&&<><div className="nav-section">GESTÃO</div><nav aria-label="Gestão">{[['/eventos','Cultos e eventos',CalendarDays],['/criancas','Crianças e famílias',Heart],['/equipe','Equipe e permissões',Users],['/notificacoes','Notificações',Bell],['/relatorios','Relatórios',ClipboardList],['/configuracoes','Configurações',Settings]].map(([path,label,Icon])=>{const Component=Icon as typeof Settings;return <NavLink key={String(path)} to={String(path)} onClick={()=>setOpen(false)}><Component size={19}/><span>{String(label)}</span></NavLink>;})}</nav></>}
 <div className="sidebar-bottom"><div className="help-card"><span><Sprout size={20}/></span><strong>Cuidar também é acolher.</strong><p>Pequenos gestos fazem uma grande diferença.</p><Link to="/instalar">Leve a Escolinha com você <ArrowUpRight size={14}/></Link></div><button className="user-menu" onClick={()=>void logout()} title="Sair da conta"><Avatar name={data.current_user.name} small/><span><strong>{data.current_user.name.split(' ')[0]} {data.current_user.name.split(' ').at(-1)}</strong><small>{role==='administrator'?'Administradora':role==='teacher'?'Professora':'Responsável'}</small></span><LogOut size={17}/></button></div></aside>
 <div className="main-wrapper"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" aria-label="Abrir menu" onClick={()=>setOpen(true)}><Menu/></button><span className="breadcrumb">Escolinha <span>/</span> <strong>{location.pathname==='/'?'Visão geral':links.find(l=>l[0]===location.pathname)?.[1]??'Ministério infantil'}</strong></span></div><div className="topbar-right">{isDemo&&<label className="demo-switch"><span className="demo-dot"/>Demonstração<select aria-label="Perfil da demonstração" value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="administrator">Administração</option><option value="teacher">Professora</option><option value="guardian">Responsável</option></select></label>}{!isDemo&&data.current_user.roles.length>1&&<select aria-label="Perfil de acesso" value={role} onChange={e=>setRole(e.target.value as typeof role)}>{data.current_user.roles.map(r=><option key={r} value={r}>{r}</option>)}</select>}<Link to="/chamados" className="notification-button icon-button" aria-label={`${calls} chamados ativos`}><Bell size={21}/>{calls>0&&<i/>}</Link><Avatar name={data.current_user.name} small/></div></header>
 {!online&&<div className="offline-banner" role="alert"><WifiOff size={17}/>Sem conexão. Operações precisam da confirmação do sistema.</div>}
 <main id="main" tabIndex={-1}><div className="event-bar"><span><span className="live-dot"/> {data.events.find(e=>e.id===selectedEvent)?.status==='open'?'ACONTECENDO HOJE':'EVENTO SELECIONADO'}</span><label><CalendarDays size={16}/><select aria-label="Culto ou evento atual" value={selectedEvent} onChange={e=>setSelectedEvent(e.target.value)}>{data.events.map(e=><option key={e.id} value={e.id}>{e.name} · {new Date(e.starts_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</option>)}</select></label><span className="event-safety"><ShieldCheck size={15}/> Um ambiente de cuidado e segurança</span></div><Outlet/></main><footer className="footer"><span>Feito para cuidar de quem mais importa.</span><span>Escolinha <span className="footer-dot">·</span> {isDemo?'Dados fictícios · nada é enviado':'Ministério infantil'}</span></footer><PushPrompt userId={data.current_user.id}/></div>
 {role==='guardian'&&<nav className="bottom-nav" aria-label="Navegação do responsável">{[['/','Início',LayoutDashboard],['/criancas','Filhos',Heart],['/chamados','Chamados',Bell],['/configuracoes','Perfil',UserRound]].map(([path,label,Icon])=>{const I=Icon as typeof QrCode;return <NavLink key={String(path)} to={String(path)} end={path==='/'}><I size={20}/>{String(label)}</NavLink>;})}</nav>}</div>;
}
