import { useEffect, useRef, useId, type ReactNode } from 'react';
import { X, ChevronRight, Sprout, Inbox, LoaderCircle } from 'lucide-react';
import { statusLabel, type Child } from '../../shared/domain';
export function Logo(){return <span className="brand"><span className="brand-icon"><Sprout size={27}/></span><span>escolinha<span className="brand-sub">UM LUGAR PARA CRESCER</span></span></span>;}
export function PageTitle({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <div className="page-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>;}
export function Badge({status,children}:{status?:string;children?:ReactNode}){return <span className={`badge badge-${status??'default'}`}><span className="status-dot"/>{children??statusLabel[status??'']??status}</span>;}
export function Avatar({name,color='green',small=false}:{name:string;color?:string;small?:boolean}){return <span className={`avatar avatar-${color} ${small?'small':''}`} aria-hidden="true">{name.split(' ').filter(Boolean).slice(0,2).map(n=>n[0]).join('')}</span>;}
export function ChildAvatar({child,color='green',small=false}:{child:Pick<Child,'name'|'photo_path'|'photo_url'>;color?:string;small?:boolean}){const photo=child.photo_url??child.photo_path;return photo?<span className={`avatar avatar-photo ${small?'small':''}`} aria-hidden="true"><img src={photo} alt=""/></span>:<Avatar name={child.name} color={color} small={small}/>;}
export function Empty({title='Nada por aqui ainda',description='Os registros aparecerão aqui.',action}:{title?:string;description?:string;action?:ReactNode}){return <div className="empty"><span><Inbox size={27}/></span><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function Loading(){return <div className="empty" role="status"><LoaderCircle className="spin"/><p>Preparando a Escolinha…</p></div>;}
export function Modal({title,description,onClose,children}:{title:string;description?:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);const id=useId();useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);return <dialog ref={ref} aria-labelledby={id} className="modal" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-heading"><div><h2 id={id}>{title}</h2>{description&&<p>{description}</p>}</div><button className="icon-button" aria-label="Fechar janela" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;}
export function Panel({title,subtitle,action,children,className=''}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}>{title&&<div className="panel-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>;}
export function More({children}:{children:ReactNode}){return <span className="more">{children}<ChevronRight size={16}/></span>;}
export function FormActions({busy,onClose,label='Salvar'}:{busy:boolean;onClose:()=>void;label?:string}){return <div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button type="submit" className="button" disabled={busy}>{busy?'Salvando…':label}</button></div>;}
export const time=(value?:string)=>value?new Date(value).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'—';
export const date=(value:string)=>new Date(value).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'});
