-- Local/homologation migration. Production execution is an explicit deployment step.
create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated, service_role;
alter default privileges in schema public revoke execute on functions from public;
alter default privileges in schema private revoke execute on functions from public;

create table public.units (id uuid primary key default gen_random_uuid(), name text not null check(length(name) between 2 and 120), slug text not null unique, timezone text not null default 'America/Sao_Paulo', active boolean not null default true, created_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id), name text not null, email text not null default '', phone text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.memberships (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id), user_id uuid not null references public.profiles(id), roles text[] not null default array['guardian']::text[] check(roles <@ array['guardian','teacher','administrator']::text[] and cardinality(roles)>0), active boolean not null default true, created_at timestamptz not null default now(), unique(unit_id,user_id));
create index memberships_user on public.memberships(user_id,unit_id);
create table public.children (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id), guardian_id uuid not null references public.profiles(id), name text not null check(length(name) between 2 and 120), birth_date date not null check(birth_date >= date '2000-01-01'), active boolean not null default true, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(unit_id,id));
create table public.child_guardians (id uuid primary key default gen_random_uuid(), unit_id uuid not null, child_id uuid not null, guardian_id uuid not null references public.profiles(id), can_manage boolean not null default false, can_check_in boolean not null default false, can_pick_up boolean not null default false, active boolean not null default true, created_at timestamptz not null default now(), foreign key(unit_id,child_id) references public.children(unit_id,id), unique(child_id,guardian_id));
create index child_guardians_user on public.child_guardians(guardian_id,unit_id,child_id);
create table public.child_care (child_id uuid primary key, unit_id uuid not null, allergies text not null default '' check(length(allergies)<=1000), medication text not null default '' check(length(medication)<=1000), needs text not null default '' check(length(needs)<=1000), notes text not null default '' check(length(notes)<=2000), updated_by uuid not null references public.profiles(id), updated_at timestamptz not null default now(), foreign key(unit_id,child_id) references public.children(unit_id,id));
create table public.authorized_people (id uuid primary key default gen_random_uuid(), unit_id uuid not null, child_id uuid not null, name text not null check(length(name) between 2 and 120), relationship text not null check(length(relationship) between 2 and 120), phone text not null default '' check(length(phone)<=25), active boolean not null default true, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), revoked_at timestamptz, foreign key(unit_id,child_id) references public.children(unit_id,id), unique(unit_id,id));
create table public.events (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id), name text not null check(length(name) between 2 and 120), starts_at timestamptz not null, status text not null default 'draft' check(status in ('open','closed','draft')), created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), unique(unit_id,id));
create table public.classes (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id), name text not null check(length(name) between 2 and 120), room text not null check(length(room) between 2 and 120), min_months int not null check(min_months>=0), max_months int not null check(max_months>min_months and max_months<=217), capacity int not null check(capacity between 1 and 200), teacher_ids uuid[] not null default '{}', color text not null default 'green' check(color in ('green','blue','orange','purple')), active boolean not null default true, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), unique(unit_id,id));
create table public.check_ins (id uuid primary key default gen_random_uuid(), unit_id uuid not null, child_id uuid not null, event_id uuid not null, class_id uuid not null, guardian_id uuid not null references public.profiles(id), status text not null default 'pending_reception' check(status in ('pending_reception','present','pickup_requested','checked_out','cancelled')), public_code text not null unique default ('E-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,16))), requested_at timestamptz not null default now(), received_at timestamptz, received_by uuid references public.profiles(id), checked_out_at timestamptz, created_by uuid not null references public.profiles(id), age_months int not null, class_name_snapshot text not null, room_snapshot text not null, foreign key(unit_id,child_id) references public.children(unit_id,id), foreign key(unit_id,event_id) references public.events(unit_id,id), foreign key(unit_id,class_id) references public.classes(unit_id,id), unique(unit_id,id));
create unique index one_active_check_in on public.check_ins(unit_id,event_id,child_id) where status in ('pending_reception','present','pickup_requested');
create index attendance_scope on public.check_ins(unit_id,event_id,class_id,status);
create table private.pickup_credentials (id uuid primary key default gen_random_uuid(), check_in_id uuid not null references public.check_ins(id), digest text not null unique, numeric_digest text unique, expires_at timestamptz not null, consumed_at timestamptz, revoked_at timestamptz, created_by uuid not null, created_at timestamptz not null default now());
create table public.check_outs (id uuid primary key default gen_random_uuid(), unit_id uuid not null, check_in_id uuid not null unique, person_id uuid not null, person_name text not null, requested_by uuid references public.profiles(id), validated_by uuid not null references public.profiles(id), completed_by uuid not null references public.profiles(id), completed_at timestamptz not null default now(), credential_id uuid not null references private.pickup_credentials(id), foreign key(unit_id,check_in_id) references public.check_ins(unit_id,id), foreign key(unit_id,person_id) references public.authorized_people(unit_id,id));
create table public.calls (id uuid primary key default gen_random_uuid(), unit_id uuid not null, attendance_id uuid not null, child_id uuid not null, guardian_id uuid not null references public.profiles(id), created_by uuid not null references public.profiles(id), reason text not null check(length(reason) between 2 and 120), note text not null default '' check(length(note)<=2000), status text not null default 'open' check(status in ('open','viewed','acknowledged','on_the_way','finalized','cancelled')), created_at timestamptz not null default now(), viewed_at timestamptz, acknowledged_at timestamptz, on_the_way_at timestamptz, finalized_at timestamptz, foreign key(unit_id,attendance_id) references public.check_ins(unit_id,id), foreign key(unit_id,child_id) references public.children(unit_id,id), unique(unit_id,id));
create unique index one_active_call on public.calls(attendance_id) where status not in ('finalized','cancelled');
create table public.call_events (id uuid primary key default gen_random_uuid(), unit_id uuid not null, call_id uuid not null, status text not null, actor_id uuid not null references public.profiles(id), created_at timestamptz not null default now(), foreign key(unit_id,call_id) references public.calls(unit_id,id));
create table public.incidents (id uuid primary key default gen_random_uuid(), unit_id uuid not null, attendance_id uuid not null, child_id uuid not null, category text not null check(length(category) between 2 and 120), description text not null check(length(description) between 5 and 3000), shared boolean not null default false, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), foreign key(unit_id,attendance_id) references public.check_ins(unit_id,id), foreign key(unit_id,child_id) references public.children(unit_id,id));
create table public.call_reasons (id uuid primary key default gen_random_uuid(),unit_id uuid not null references public.units(id),label text not null check(length(label) between 2 and 120),active boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(unit_id,label));
create table public.incident_revisions (id uuid primary key default gen_random_uuid(),unit_id uuid not null references public.units(id),incident_id uuid not null references public.incidents(id),description text not null,reason text not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.notification_preferences (unit_id uuid not null references public.units(id), user_id uuid not null references public.profiles(id), email boolean not null default true, push boolean not null default false, sound boolean not null default false, primary key(unit_id,user_id));
create table public.unit_settings (unit_id uuid primary key references public.units(id), email_delay_minutes int not null default 2 check(email_delay_minutes between 1 and 60), phone_delay_minutes int not null default 5 check(phone_delay_minutes>email_delay_minutes and phone_delay_minutes<=120));
create table public.deliveries (id uuid primary key default gen_random_uuid(), unit_id uuid not null, call_id uuid not null, channel text not null check(channel in ('internal','push','email')), status text not null default 'pending' check(status in ('pending','accepted','delivered','failed','unknown','cancelled')), attempts int not null default 0, error text, provider_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(unit_id,call_id) references public.calls(unit_id,id));
create table private.outbox_jobs (id uuid primary key default gen_random_uuid(), delivery_id uuid not null references public.deliveries(id), call_id uuid not null references public.calls(id), run_after timestamptz not null default now(), status text not null default 'pending' check(status in ('pending','processing','completed','cancelled','dead_letter')), lease_token uuid, lease_until timestamptz, attempts int not null default 0, unique(delivery_id));
create index due_jobs on private.outbox_jobs(status,run_after);
create table private.delivery_attempts (id uuid primary key default gen_random_uuid(), job_id uuid not null references private.outbox_jobs(id), lease_token uuid not null, number int not null, result jsonb not null, created_at timestamptz not null default now(), unique(job_id,lease_token));
create table private.push_subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), session_hash text not null, endpoint text not null unique, subscription jsonb not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.legal_document_versions (id text primary key, kind text not null, version text not null, published boolean not null default false, content text not null, created_at timestamptz not null default now());
create table public.consents (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id), user_id uuid not null references public.profiles(id), document_id text not null references public.legal_document_versions(id), accepted_at timestamptz not null default now(), withdrawn_at timestamptz, unique(user_id,unit_id,document_id));
create table public.privacy_requests (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id), user_id uuid not null references public.profiles(id), kind text not null check(kind in ('access','correction','deletion')), status text not null default 'pending', created_at timestamptz not null default now());
create table public.integration_settings (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id), provider text not null default 'holyrics', enabled boolean not null default false, mode text not null default 'media_approval' check(mode in ('automatic','media_approval')), duration_seconds int not null default 15 check(duration_seconds between 5 and 120), unique(unit_id,provider));
create table public.integration_logs (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id), provider text not null, public_code text not null, status text not null, connection_status text not null default 'unknown', error_code text, created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id), actor_id uuid references public.profiles(id), action text not null, entity_id uuid, created_at timestamptz not null default now());
create index audit_period on public.audit_logs(unit_id,created_at);
create table public.change_signals (user_id uuid primary key references public.profiles(id), changed_at timestamptz not null default now());
create table private.idempotency (unit_id uuid not null, actor_id uuid not null, key uuid not null, request jsonb not null, result jsonb not null, created_at timestamptz not null default now(), primary key(unit_id,actor_id,key));
create table private.rate_limits (key text primary key, count int not null default 1, window_start timestamptz not null default now());
create table private.server_sessions (hash text primary key, user_id uuid not null references public.profiles(id), encrypted_tokens text not null, expires_at timestamptz not null, revoked_at timestamptz, updated_at timestamptz not null default now());

create function private.member(u uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.memberships m join public.units x on x.id=m.unit_id where m.unit_id=u and m.user_id=auth.uid() and m.active and x.active) $$;
create function private.admin(u uuid) returns boolean language sql stable security definer set search_path='' as $$ select private.member(u) and exists(select 1 from public.memberships m where m.unit_id=u and m.user_id=auth.uid() and 'administrator'=any(m.roles)) $$;
create function private.teacher(u uuid,c uuid) returns boolean language sql stable security definer set search_path='' as $$ select private.member(u) and exists(select 1 from public.classes r join public.memberships m on m.unit_id=r.unit_id and m.user_id=auth.uid() where r.id=c and r.unit_id=u and r.active and auth.uid()=any(r.teacher_ids) and 'teacher'=any(m.roles)) $$;
create function private.guardian(u uuid,c uuid,permission text default 'read') returns boolean language sql stable security definer set search_path='' as $$ select private.member(u) and exists(select 1 from public.child_guardians g where g.unit_id=u and g.child_id=c and g.guardian_id=auth.uid() and g.active and case permission when 'manage' then g.can_manage when 'checkin' then g.can_check_in when 'pickup' then g.can_pick_up else true end) $$;
create function private.child_access(u uuid,c uuid) returns boolean language sql stable security definer set search_path='' as $$ select private.admin(u) or private.guardian(u,c) or exists(select 1 from public.check_ins a where a.unit_id=u and a.child_id=c and private.teacher(u,a.class_id)) $$;
create function private.care_access(u uuid,c uuid) returns boolean language sql stable security definer set search_path='' as $$ select private.guardian(u,c,'manage') or exists(select 1 from public.check_ins a where a.unit_id=u and a.child_id=c and a.status in ('pending_reception','present','pickup_requested') and private.teacher(u,a.class_id)) $$;
create function private.staff_attendance(u uuid,a uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.check_ins i where i.unit_id=u and i.id=a and (private.admin(u) or private.teacher(u,i.class_id))) $$;
create function private.call_access(u uuid,c uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.calls x where x.id=c and x.unit_id=u and ((x.guardian_id=auth.uid() and private.guardian(u,x.child_id)) or private.staff_attendance(u,x.attendance_id))) $$;
create function private.signal(u uuid) returns void language sql security definer set search_path='' as $$ insert into public.change_signals(user_id,changed_at) select m.user_id,clock_timestamp() from public.memberships m where m.unit_id=u and m.active on conflict(user_id) do update set changed_at=excluded.changed_at $$;
revoke all on all functions in schema private from public, anon;
grant execute on function private.member(uuid),private.admin(uuid),private.teacher(uuid,uuid),private.guardian(uuid,uuid,text),private.child_access(uuid,uuid),private.care_access(uuid,uuid),private.staff_attendance(uuid,uuid),private.call_access(uuid,uuid) to authenticated;

-- No direct client writes. Commands below enforce transitions, authorization and audit atomically.
do $$ declare t text; begin for t in select tablename from pg_tables where schemaname='public' loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on public.%I from anon, authenticated',t); execute format('grant select on public.%I to authenticated',t); end loop; end $$;
create policy unit_read on public.units for select to authenticated using(private.member(id));
create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or exists(select 1 from public.memberships m where m.user_id=profiles.id and private.admin(m.unit_id)));
create policy membership_read on public.memberships for select to authenticated using(user_id=auth.uid() or private.admin(unit_id));
create policy child_read on public.children for select to authenticated using(private.child_access(unit_id,id));
create policy guardians_read on public.child_guardians for select to authenticated using(private.guardian(unit_id,child_id) or private.admin(unit_id));
create policy care_read on public.child_care for select to authenticated using(private.care_access(unit_id,child_id));
create policy people_read on public.authorized_people for select to authenticated using(private.child_access(unit_id,child_id));
create policy events_read on public.events for select to authenticated using(private.member(unit_id));
create policy classes_read on public.classes for select to authenticated using(private.member(unit_id) and (private.admin(unit_id) or private.teacher(unit_id,id) or exists(select 1 from public.memberships m where m.unit_id=classes.unit_id and m.user_id=auth.uid() and 'guardian'=any(m.roles))));
create policy attendance_read on public.check_ins for select to authenticated using(private.guardian(unit_id,child_id) or private.staff_attendance(unit_id,id));
create policy checkout_read on public.check_outs for select to authenticated using(exists(select 1 from public.check_ins a where a.id=check_in_id));
create policy calls_read on public.calls for select to authenticated using(private.call_access(unit_id,id));
create policy call_events_read on public.call_events for select to authenticated using(private.call_access(unit_id,call_id));
create policy incidents_read on public.incidents for select to authenticated using(private.teacher(unit_id,(select class_id from public.check_ins where id=attendance_id)) or (shared and private.guardian(unit_id,child_id)));
create policy reasons_read on public.call_reasons for select to authenticated using(private.member(unit_id));
create policy revisions_read on public.incident_revisions for select to authenticated using(exists(select 1 from public.incidents i where i.id=incident_id and private.teacher(unit_id,(select class_id from public.check_ins a where a.id=i.attendance_id))));
create policy prefs_read on public.notification_preferences for select to authenticated using(user_id=auth.uid() and private.member(unit_id));
create policy settings_read on public.unit_settings for select to authenticated using(private.member(unit_id));
create policy deliveries_read on public.deliveries for select to authenticated using(private.call_access(unit_id,call_id));
create policy documents_read on public.legal_document_versions for select to authenticated using(published);
create policy consent_read on public.consents for select to authenticated using(user_id=auth.uid() or private.admin(unit_id));
create policy privacy_read on public.privacy_requests for select to authenticated using(user_id=auth.uid() or private.admin(unit_id));
create policy integration_read on public.integration_settings for select to authenticated using(private.admin(unit_id));
create policy integration_log_read on public.integration_logs for select to authenticated using(private.admin(unit_id));
create policy audit_read on public.audit_logs for select to authenticated using(private.admin(unit_id));
create policy signal_read on public.change_signals for select to authenticated using(user_id=auth.uid());

-- Snapshot is INVOKER and therefore uses each underlying table's RLS.
create function public.app_snapshot(p_unit uuid) returns jsonb language plpgsql security invoker set search_path='' as $$
declare result jsonb; begin
 if not private.member(p_unit) then raise exception 'Acesso à unidade não autorizado.' using errcode='42501'; end if;
 select jsonb_build_object(
 'call_reasons',coalesce((select jsonb_agg(to_jsonb(r)) from public.call_reasons r where unit_id=p_unit),'[]'::jsonb),
 'unit_id',p_unit,'unit_name',(select name from public.units where id=p_unit),
 'current_user',(select to_jsonb(p)||jsonb_build_object('roles',m.roles,'active',m.active) from public.profiles p join public.memberships m on m.user_id=p.id and m.unit_id=p_unit where p.id=auth.uid()),
 'profiles',coalesce((select jsonb_agg(to_jsonb(p)||jsonb_build_object('roles',m.roles,'active',m.active)) from public.profiles p join public.memberships m on m.user_id=p.id where m.unit_id=p_unit),'[]'::jsonb),
 'children',coalesce((select jsonb_agg(to_jsonb(c)||jsonb_build_object('guardian_name',coalesce((select name from public.profiles where id=c.guardian_id),'Responsável'),'allergies',coalesce(h.allergies,''),'medication',coalesce(h.medication,''),'needs',coalesce(h.needs,''),'notes',coalesce(h.notes,''))) from public.children c left join public.child_care h on h.child_id=c.id where c.unit_id=p_unit),'[]'::jsonb),
 'people',coalesce((select jsonb_agg(to_jsonb(p)) from public.authorized_people p where unit_id=p_unit),'[]'::jsonb),
 'events',coalesce((select jsonb_agg(to_jsonb(e) order by starts_at desc) from public.events e where unit_id=p_unit),'[]'::jsonb),
 'classes',coalesce((select jsonb_agg(to_jsonb(c) order by min_months) from public.classes c where unit_id=p_unit),'[]'::jsonb),
 'attendance',coalesce((select jsonb_agg(to_jsonb(a)||jsonb_build_object('pickup_person',o.person_name,'validated_by',o.validated_by)) from public.check_ins a left join public.check_outs o on o.check_in_id=a.id where a.unit_id=p_unit),'[]'::jsonb),
 'calls',coalesce((select jsonb_agg(to_jsonb(c) order by created_at desc) from public.calls c where unit_id=p_unit),'[]'::jsonb),
 'incidents',coalesce((select jsonb_agg(to_jsonb(i) order by created_at desc) from public.incidents i where unit_id=p_unit),'[]'::jsonb),
 'deliveries',coalesce((select jsonb_agg(to_jsonb(d) order by created_at desc) from public.deliveries d where unit_id=p_unit),'[]'::jsonb),
 'audit',coalesce((select jsonb_agg(to_jsonb(a)||jsonb_build_object('actor',coalesce((select name from public.profiles where id=a.actor_id),'Sistema'))) from (select * from public.audit_logs where unit_id=p_unit order by created_at desc limit 100) a),'[]'::jsonb),
 'settings',jsonb_build_object('email_delay_minutes',coalesce((select email_delay_minutes from public.unit_settings where unit_id=p_unit),2),'phone_delay_minutes',coalesce((select phone_delay_minutes from public.unit_settings where unit_id=p_unit),5),'holyrics_enabled',false,'email',coalesce((select email from public.notification_preferences where unit_id=p_unit and user_id=auth.uid()),true),'push',coalesce((select push from public.notification_preferences where unit_id=p_unit and user_id=auth.uid()),false),'sound',coalesce((select sound from public.notification_preferences where unit_id=p_unit and user_id=auth.uid()),false))) into result;
 return result; end $$;
grant execute on function public.app_snapshot(uuid) to authenticated;
