-- Proposta para homologação. Não aplicar automaticamente nem em produção.
create table public.media_alerts (
  id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.units(id),
  event_id uuid not null, call_id uuid not null unique, public_code text not null,
  public_message text not null, priority text not null default 'normal' check(priority in ('normal','urgent')),
  status text not null default 'pending' check(status in ('pending','received_by_connector','awaiting_approval','approved','sending','sent_to_holyrics','rejected','failed','cancelled','expired')),
  connector_id text, received_at timestamptz, approved_at timestamptz, displayed_at timestamptz,
  rejected_at timestamptz, attempts int not null default 0, last_error text, expires_at timestamptz not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  foreign key(unit_id,event_id) references public.events(unit_id,id), foreign key(unit_id,call_id) references public.calls(unit_id,id),
  check(public_code ~ '^E-[A-Z0-9]{3,32}$'), check(length(public_message) <= 300), check(length(coalesce(last_error,'')) <= 200)
);
create index media_alerts_queue on public.media_alerts(unit_id,status,created_at desc);
create table private.media_connectors (id text primary key, unit_id uuid not null references public.units(id), user_id uuid not null references public.profiles(id), active boolean not null default true, created_at timestamptz not null default now(), unique(unit_id,user_id));
create function private.media_connector(u uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from private.media_connectors where unit_id=u and user_id=auth.uid() and active) $$;
create function private.media_alert_message(code text) returns text language sql immutable as $$ select 'ESCOLINHA — Responsável pelo código '||code||', favor comparecer à recepção.' $$;
create function private.create_media_alert() returns trigger language plpgsql security definer set search_path='' as $$ declare a public.check_ins; e public.events; begin select * into a from public.check_ins where id=new.attendance_id and unit_id=new.unit_id; select * into e from public.events where id=a.event_id and unit_id=new.unit_id; insert into public.media_alerts(unit_id,event_id,call_id,public_code,public_message,expires_at) values(new.unit_id,a.event_id,new.id,a.public_code,private.media_alert_message(a.public_code),least(new.created_at+interval '2 hours',e.starts_at+interval '12 hours')) on conflict(call_id) do nothing; return new; end $$;
create trigger calls_create_media_alert after insert on public.calls for each row execute function private.create_media_alert();
create function private.close_media_alert() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.status in ('finalized','cancelled') then update public.media_alerts set status=case when status in ('sent_to_holyrics','rejected') then status else 'cancelled' end,updated_at=now(),last_error=case when new.status='finalized' then 'CHAMADO_FINALIZADO' else 'CHAMADO_CANCELADO' end where call_id=new.id and status not in ('sent_to_holyrics','rejected','cancelled'); end if; return new; end $$;
create trigger calls_close_media_alert after update of status on public.calls for each row execute function private.close_media_alert();
alter table public.media_alerts enable row level security;
revoke all on public.media_alerts from anon, authenticated;
grant select on public.media_alerts to authenticated;
create policy media_connector_read on public.media_alerts for select to authenticated using(private.media_connector(unit_id));
create function public.media_alert_transition(p_alert uuid,p_status text,p_connector text,p_error text default null) returns jsonb language plpgsql security invoker set search_path='' as $$ declare a public.media_alerts; begin select * into a from public.media_alerts where id=p_alert for update; if not found or not private.media_connector(a.unit_id) then raise exception 'Alerta não autorizado.' using errcode='42501'; end if; if a.status in ('cancelled','expired','rejected','sent_to_holyrics') then return jsonb_build_object('error','Alerta encerrado.'); end if; if p_status='sending' then update public.media_alerts set status='sending',attempts=attempts+1,connector_id=p_connector,updated_at=now() where id=a.id and attempts<4; elsif p_status='sent_to_holyrics' then update public.media_alerts set status=p_status,displayed_at=now(),updated_at=now(),last_error=null,connector_id=p_connector where id=a.id and status='sending'; elsif p_status='failed' then update public.media_alerts set status='failed',last_error=left(p_error,200),updated_at=now(),connector_id=p_connector where id=a.id and status='sending'; elsif p_status='approved' then update public.media_alerts set status='approved',approved_at=now(),connector_id=p_connector,updated_at=now() where id=a.id and status in ('pending','received_by_connector','awaiting_approval','failed'); elsif p_status='received_by_connector' then update public.media_alerts set status='awaiting_approval',received_at=coalesce(received_at,now()),connector_id=p_connector,updated_at=now() where id=a.id and status='pending'; elsif p_status in ('rejected','cancelled') then update public.media_alerts set status=p_status,rejected_at=case when p_status='rejected' then now() else rejected_at end,updated_at=now(),connector_id=p_connector where id=a.id and status not in ('sending','sent_to_holyrics'); else raise exception 'Transição inválida.'; end if; return jsonb_build_object('ok',true); end $$;
revoke all on function public.media_alert_transition(uuid,text,text,text) from public,anon; grant execute on function public.media_alert_transition(uuid,text,text,text) to authenticated;
do $$ begin if exists(select 1 from pg_publication where pubname='supabase_realtime') then alter publication supabase_realtime add table public.media_alerts; end if; end $$;
